[package]
name = "soulxtech"
license = "MIT OR Apache-2.0"
description = "Testing cargo publish while reading the book."
version = "0.1.0"
edition = "2021"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
